import React from 'react';

const SummaryCard = ({ summary }) => {
  const downloadReport = () => {
    if (!summary) return;

    const content = `
PATIENT SUMMARY REPORT
=====================================
Patient: ${summary.patient_name}
Age: ${summary.age} years
Gender: ${summary.gender}
Generated by: ${summary.generated_by_name}
Date: ${new Date(summary.created_at).toLocaleString()}

=====================================
MEDICAL HISTORY
=====================================
${summary.history || 'No medical history recorded'}

=====================================
DOCTOR'S SUMMARY
=====================================
${summary.summary_text}

=====================================
NOTES
=====================================
This is a digitally generated summary report.
For medical emergencies, please contact your healthcare provider immediately.
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Patient_Summary_${summary.patient_name?.replace(/\s+/g, '_')}_${summary.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (!summary) {
    return (
      <div className="summary-card">
        <div className="summary-card-body empty-state">
          <p>No summary available for this patient.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="summary-card">
      <div className="summary-card-header">
        <div className="summary-patient-info">
          <div className="summary-avatar">
            {summary.patient_name?.charAt(0).toUpperCase()}
          </div>
          <div>
            <h2>{summary.patient_name}</h2>
            <span className="patient-badge">{summary.gender}, {summary.age} years</span>
          </div>
        </div>
        <div className="summary-meta">
          <small>Generated by</small>
          <strong>{summary.generated_by_name}</strong>
          <small>{new Date(summary.created_at).toLocaleDateString()}</small>
        </div>
      </div>

      <div className="summary-card-body">
        <div className="summary-section">
          <h4>Medical History</h4>
          <div className="summary-section-content">
            {summary.history || 'No medical history recorded'}
          </div>
        </div>

        <div className="summary-section">
          <h4>Doctor Summary</h4>
          <div className="summary-section-content highlight">
            {summary.summary_text}
          </div>
        </div>

        <div className="summary-actions">
          <button className="btn-primary btn-sm" onClick={downloadReport}>
            Download Report
          </button>
        </div>
      </div>
    </div>
  );
};

export default SummaryCard;