import React from 'react';

const SummaryCard = ({ summary }) => {
    if (!summary) {
        return (
            <div className="card shadow-sm border-0">
                <div className="card-body text-center text-muted py-5">
                    <div className="mb-3">📋</div>
                    <p>No summary available for this patient.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="card shadow-sm border-0">
            <div className="card-header bg-primary text-white">
                <h5 className="mb-0">Patient Summary Report</h5>
            </div>
            <div className="card-body">
                <div className="row mb-4">
                    <div className="col-md-6">
                        <div className="d-flex align-items-center mb-3">
                            <div 
                                className="rounded-circle bg-primary text-white d-flex align-items-center justify-content-center me-3"
                                style={{ width: '60px', height: '60px', fontSize: '1.5rem' }}
                            >
                                {summary.patient_name?.charAt(0).toUpperCase()}
                            </div>
                            <div>
                                <h4 className="mb-0">{summary.patient_name}</h4>
                                <span className="badge bg-light text-dark">
                                    {summary.gender}, {summary.age} years
                                </span>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-6 text-md-end">
                        <small className="text-muted d-block">Generated by</small>
                        <strong>{summary.generated_by_name}</strong>
                        <br />
                        <small className="text-muted">
                            {new Date(summary.created_at).toLocaleDateString()}
                        </small>
                    </div>
                </div>

                <div className="mb-4">
                    <h6 className="text-muted text-uppercase mb-2" style={{ fontSize: '0.75rem' }}>
                        Medical History
                    </h6>
                    <div className="p-3 bg-light rounded">
                        {summary.history || 'No medical history recorded'}
                    </div>
                </div>

                <div className="mb-4">
                    <h6 className="text-muted text-uppercase mb-2" style={{ fontSize: '0.75rem' }}>
                        Doctor Summary
                    </h6>
                    <div className="p-3 border-start border-4 border-primary bg-light rounded">
                        <p className="mb-0" style={{ lineHeight: '1.6' }}>
                            {summary.summary_text}
                        </p>
                    </div>
                </div>

                <div className="d-flex justify-content-end">
                    <button className="btn btn-outline-primary btn-sm">
                        📥 Download Report
                    </button>
                </div>
            </div>
        </div>
    );
};

export default SummaryCard;
