import React, { useEffect, useState, useCallback } from "react";
import { patientAPI } from "../services/api";
import "../styles/Dashboard.css";

const PatientDashboard = ({ user }) => {
  const [patient, setPatient] = useState(null);
  const [prescriptions, setPrescriptions] = useState([]);
  const [claims, setClaims] = useState([]);
  const [summaries, setSummaries] = useState([]);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({
    prescriptions: 0,
    claims: 0,
    summaries: 0,
    reports: 0,
  });

  const fetchPatientData = useCallback(async () => {
    try {
      setLoading(true);
      const patientRes = await patientAPI.getAll(user?.id, user?.role);
      const patientData = patientRes.data.patients?.[0];
      setPatient(patientData);

      if (patientData) {
        const detailsRes = await patientAPI.getById(
          patientData.id,
          user?.id,
          user?.role
        );
        if (detailsRes.data.success) {
          const prescriptionsData = detailsRes.data.patient.prescriptions || [];
          const claimsData = detailsRes.data.patient.claims || [];
          const summariesData = detailsRes.data.patient.summaries || [];
          const reportsData = detailsRes.data.patient.reports || [];

          setPrescriptions(prescriptionsData);
          setClaims(claimsData);
          setSummaries(summariesData);
          setReports(reportsData);

          setStats({
            prescriptions: prescriptionsData.length,
            claims: claimsData.length,
            summaries: summariesData.length,
            reports: reportsData.length,
          });
        }
      }
    } catch (err) {
      console.error("Error fetching patient data:", err);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    fetchPatientData();
  }, [fetchPatientData]);

  // Helper: Generate PDF via print window
  const generatePDF = (content, filename) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to download files.');
      return;
    }
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${filename}</title>
        <style>
          body {
            font-family: 'Courier New', monospace;
            font-size: 12px;
            line-height: 1.4;
            margin: 20px;
            color: #333;
          }
          h1 { text-align: center; color: #2c3e50; margin-bottom: 20px; }
          .header { border-bottom: 2px solid #2c3e50; padding-bottom: 10px; margin-bottom: 20px; }
          .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; }
          @media print { body { margin: 10px; } }
        </style>
      </head>
      <body>
        <h1>${filename.split('_')[0].replace(/_/g, ' ').toUpperCase()}</h1>
        <div class="header">
          <strong>SarvCare Healthcare System</strong><br>
          Generated on: ${new Date().toLocaleString()}
        </div>
        <pre style="white-space: pre-wrap;">${content}</pre>
        <div class="footer">
          This is a digitally generated document. For medical emergencies, please contact your healthcare provider immediately.
        </div>
        <script>
          window.onload = function() {
            setTimeout(function() { window.print(); window.close(); }, 500);
          };
        </script>
      </body>
      </html>
    `;
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  // Download prescription as PDF
  const downloadPrescription = (prescription) => {
    const content = `
PRESCRIPTION
=====================================
Patient: ${patient?.name || user?.name || 'N/A'}
Email: ${patient?.email || user?.email || 'N/A'}
ABHA ID: ${patient?.abha_id || 'N/A'}
Date: ${new Date(prescription.created_at).toLocaleDateString()}
Doctor: Dr. ${prescription.doctor_name || 'N/A'}

=====================================
MEDICATION DETAILS
=====================================
Medication: ${prescription.medication || 'N/A'}
Dosage: ${prescription.dosage || 'Not specified'}
Instructions: ${prescription.instructions || prescription.notes || 'No instructions provided'}

=====================================
NOTES
=====================================
This is a digitally generated prescription.
Please consult your doctor for any questions.
    `.trim();
    generatePDF(content, `Prescription_${prescription.id}.pdf`);
  };

  // Download medical summary as PDF
  const downloadSummary = (summary) => {
    const content = `
MEDICAL SUMMARY
=====================================
Patient: ${patient?.name || user?.name || 'N/A'}
Email: ${patient?.email || user?.email || 'N/A'}
ABHA ID: ${patient?.abha_id || user?.abha_id || 'N/A'}
Date: ${new Date(summary.created_at).toLocaleDateString()}
Generated by: Dr. ${summary.generated_by_name || 'N/A'}

=====================================
SUMMARY
=====================================
${summary.summary_text || 'No summary content available'}

=====================================
NOTES
=====================================
This is a digitally generated medical summary.
Please consult your doctor for any questions.
    `.trim();
    generatePDF(content, `Medical_Summary_${summary.id}.pdf`);
  };

  // Download report (file from backend)
  const downloadReport = (report) => {
    if (!report.file_url) {
      alert('No file available for this report. Please contact your doctor.');
      return;
    }
    let downloadUrl = report.file_url;
    if (!downloadUrl.startsWith('http')) {
      downloadUrl = `${window.location.origin}${downloadUrl}`;
    }
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = report.report_title || `Report_${report.id}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (loading) {
    return (
      <div className="dashboard-loading">
        <div className="spinner"></div>
        <p>Loading your medical records...</p>
      </div>
    );
  }

  return (
    <div className="dashboard-container">
      {/* Header */}
      <div className="dashboard-header">
        <div className="dashboard-header-content">
          <h1>Welcome back, {user?.name}!</h1>
          <p>Here's your medical records overview</p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="stats-grid">
        <div className="stat-card primary">
          <div className="stat-content">
            <div className="stat-info">
              <h3>{stats.prescriptions}</h3>
              <p>Prescriptions</p>
            </div>
          </div>
        </div>
        <div className="stat-card success">
          <div className="stat-content">
            <div className="stat-info">
              <h3>{stats.claims}</h3>
              <p>Insurance Claims</p>
            </div>
          </div>
        </div>
        <div className="stat-card info">
          <div className="stat-content">
            <div className="stat-info">
              <h3>{stats.summaries}</h3>
              <p>Medical Summaries</p>
            </div>
          </div>
        </div>
        <div className="stat-card warning">
          <div className="stat-content">
            <div className="stat-info">
              <h3>{stats.reports}</h3>
              <p>Medical Reports</p>
            </div>
          </div>
        </div>
      </div>

      {/* Prescriptions Section */}
      <div className="dashboard-section">
        <div className="dashboard-section-header">
          <h2 className="dashboard-section-title">My Prescriptions ({prescriptions.length})</h2>
        </div>
        <div className="dashboard-section-body">
          {prescriptions.length === 0 ? (
            <div className="empty-state">
              <h3>No prescriptions found</h3>
              <p>No prescriptions have been recorded for you yet.</p>
            </div>
          ) : (
            <div className="prescription-grid">
              {prescriptions.map((prescription) => (
                <div key={prescription.id} className="prescription-card">
                  <div className="prescription-header">
                    <span className="prescription-date">
                      {new Date(prescription.created_at).toLocaleDateString()}
                    </span>
                    <span className="prescription-doctor">Dr. {prescription.doctor_name}</span>
                  </div>
                  <div className="prescription-content">
                    <h4>{prescription.medication}</h4>
                    <p><strong>Dosage:</strong> {prescription.dosage || 'Not specified'}</p>
                    <p><strong>Instructions:</strong> {prescription.instructions || prescription.notes || 'No instructions provided'}</p>
                    <div className="prescription-actions">
                      <button className="btn-primary btn-sm" onClick={() => downloadPrescription(prescription)}>
                        Download PDF
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Medical Summaries Section */}
      <div className="dashboard-section">
        <div className="dashboard-section-header">
          <h2 className="dashboard-section-title">Medical Summaries ({summaries.length})</h2>
        </div>
        <div className="dashboard-section-body">
          {summaries.length === 0 ? (
            <div className="empty-state">
              <h3>No medical summaries available</h3>
              <p>No medical summaries have been generated yet.</p>
            </div>
          ) : (
            <div className="summary-grid">
              {summaries.map((summary) => (
                <div key={summary.id} className="summary-card">
                  <div className="summary-header">
                    <span className="summary-date">{new Date(summary.created_at).toLocaleDateString()}</span>
                    <span className="summary-doctor m2">Dr. {summary.generated_by_name}</span>
                  </div>
                  <div className="summary-content">
                    <p className="m-3">{summary.summary_text}</p>
                    <div className="summary-actions">
                      <button className="btn-primary btn-sm" onClick={() => downloadSummary(summary)}>
                        Download Report
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Medical Reports Section */}
      <div className="dashboard-section">
        <div className="dashboard-section-header">
          <h2 className="dashboard-section-title">Medical Reports ({reports.length})</h2>
        </div>
        <div className="dashboard-section-body">
          {reports.length === 0 ? (
            <div className="empty-state">
              <h3>No medical reports available</h3>
              <p>No medical reports have been uploaded by your doctor yet.</p>
            </div>
          ) : (
            <div className="report-grid">
              {reports.map((report) => (
                <div key={report.id} className="report-card">
                  <div className="report-header">
                    <span className="report-date">{new Date(report.created_at).toLocaleDateString()}</span>
                    <span className="report-doctor">Dr. {report.uploaded_by_name}</span>
                  </div>
                  <div className="report-content">
                    <h4>{report.report_title || 'Medical Report'}</h4>
                    <p><strong>Type:</strong> {report.report_type || 'Medical Report'}</p>
                    <p><strong>Description:</strong> {report.description || 'No description available'}</p>
                    <div className="report-actions">
                      <button className="btn-primary btn-sm" onClick={() => downloadReport(report)}>
                        Download Report
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Insurance Claims Section */}
      <div className="dashboard-section">
        <div className="dashboard-section-header">
          <h2 className="dashboard-section-title">Insurance Claims ({claims.length})</h2>
        </div>
        <div className="dashboard-section-body">
          {claims.length === 0 ? (
            <div className="empty-state">
              <h3>No insurance claims found</h3>
              <p>No insurance claims have been submitted yet.</p>
            </div>
          ) : (
            <div className="claim-grid">
              {claims.map((claim) => (
                <div key={claim.id} className="claim-card">
                  <div className="claim-header">
                    <span className="claim-id">#{claim.id}</span>
                    <span className={`claim-status status-${claim.status}`}>{claim.status}</span>
                    <span className="claim-date">{new Date(claim.created_at).toLocaleDateString()}</span>
                  </div>
                  <div className="claim-content">
                    <h4>{claim.treatment || 'Medical Treatment'}</h4>
                    <p>{claim.description || 'No description available'}</p>
                    <p><strong>Amount:</strong> ₹{parseFloat(claim.cost || 0).toLocaleString('en-IN')}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default PatientDashboard;