import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { patientAPI } from '../services/api';
import SummaryCard from '../components/SummaryCard';
import '../styles/Dashboard.css';

const SummaryPage = ({ user }) => {
  const { patientId } = useParams();
  const navigate = useNavigate();
  const [patient, setPatient] = useState(null);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const downloadCompleteReport = () => {
    if (!patient) return;

    const content = `
COMPLETE PATIENT REPORT
=====================================
Patient: ${patient.name}
Age: ${patient.age} years
Gender: ${patient.gender}
ABHA ID: ${patient.abha_id || 'N/A'}
Email: ${patient.email}
Report Generated: ${new Date().toLocaleString()}

=====================================
MEDICAL HISTORY
=====================================
${patient.history || 'No medical history recorded'}

=====================================
DOCTOR'S SUMMARY
=====================================
${summary?.summary_text || 'No summary available'}
Generated by: ${summary?.generated_by_name || 'N/A'}
Generated on: ${summary ? new Date(summary.created_at).toLocaleString() : 'N/A'}

=====================================
PRESCRIPTIONS (${patient.prescriptions?.length || 0})
=====================================
${patient.prescriptions?.length > 0
      ? patient.prescriptions.map(p => `
Medication: ${p.medication}
Dosage: ${p.dosage || 'Not specified'}
Instructions: ${p.notes || 'No instructions'}
Prescribed by: ${p.doctor_name}
Date: ${new Date(p.created_at).toLocaleDateString()}
---`).join('\n')
      : 'No prescriptions recorded'
    }

=====================================
CLAIMS HISTORY (${patient.claims?.length || 0})
=====================================
${patient.claims?.length > 0
      ? patient.claims.map(c => `
Treatment: ${c.treatment}
Description: ${c.description || 'No description'}
Cost: ₹${parseFloat(c.cost || 0).toLocaleString('en-IN')}
Status: ${c.status}
Submitted: ${new Date(c.created_at).toLocaleDateString()}
---`).join('\n')
      : 'No claims history'
    }

=====================================
NOTES
=====================================
This is a digitally generated complete patient report.
For medical emergencies, please contact your healthcare provider immediately.
Generated by SarvCare Healthcare Management System.
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Complete_Patient_Report_${patient.name?.replace(/\s+/g, '_')}_${patientId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  useEffect(() => {
    if (patientId) fetchPatientData();
  }, [patientId]);

  const fetchPatientData = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await patientAPI.getById(patientId, user?.id, user?.role);
      if (response.data.success) {
        setPatient(response.data.patient);
        setSummary(response.data.patient.summaries?.[0] || null);
      }
    } catch (err) {
      console.error('Error fetching patient data:', err);
      setError('Failed to load patient data. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => window.print();

  if (loading) {
    return (
      <div className="dashboard-loading">
        <div className="spinner"></div>
        <p>Loading patient summary...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="alert-error">
        <span>{error}</span>
        <button className="btn-secondary btn-sm" onClick={fetchPatientData}>Retry</button>
      </div>
    );
  }

  if (!patient) {
    return (
      <div className="alert-warning">
        <span>Patient not found.</span>
        <button className="btn-primary btn-sm" onClick={() => navigate('/patient')}>Back to Patients</button>
      </div>
    );
  }

  return (
    <div className="summary-page-container">
      <div className="summary-page-header">
        <div>
          <button className="btn-secondary btn-sm" onClick={() => navigate(-1)}>← Back</button>
          <h1>Patient Summary Report</h1>
        </div>
        <div className="summary-actions">
          <button className="btn-primary" onClick={downloadCompleteReport}>Download Complete Report</button>
          <button className="btn-secondary" onClick={handlePrint}>Print Report</button>
        </div>
      </div>

      <div className="summary-main">
        <SummaryCard
          summary={summary ? {
            ...summary,
            patient_name: patient.name,
            age: patient.age,
            gender: patient.gender,
            history: patient.history
          } : null}
        />
      </div>

      <div className="summary-details-grid">
        <div className="summary-card">
          <div className="summary-card-header">
            <h3>Prescriptions ({patient.prescriptions?.length || 0})</h3>
          </div>
          <div className="summary-card-body">
            {patient.prescriptions?.length > 0 ? (
              <div className="prescriptions-list">
                {patient.prescriptions.map(p => (
                  <div key={p.id} className="prescription-item">
                    <div className="prescription-header">
                      <strong>{p.medication}</strong>
                      <span className="date">{new Date(p.created_at).toLocaleDateString()}</span>
                    </div>
                    <p>Dosage: {p.dosage || 'Not specified'}</p>
                    {p.notes && <small>{p.notes}</small>}
                    <small className="text-muted">Prescribed by: Dr. {p.doctor_name}</small>
                  </div>
                ))}
              </div>
            ) : (
              <p className="empty-message">No prescriptions recorded</p>
            )}
          </div>
        </div>

        <div className="summary-card">
          <div className="summary-card-header">
            <h3>Claims History ({patient.claims?.length || 0})</h3>
          </div>
          <div className="summary-card-body">
            {patient.claims?.length > 0 ? (
              <div className="claims-list">
                {patient.claims.map(c => (
                  <div key={c.id} className="claim-item">
                    <div className="claim-header">
                      <strong>{c.treatment}</strong>
                      <span className={`claim-status status-${c.status}`}>{c.status}</span>
                    </div>
                    <p>{c.description}</p>
                    <div className="claim-footer">
                      <span>Amount: ₹{parseFloat(c.cost || 0).toLocaleString('en-IN')}</span>
                      <span className="date">Submitted: {new Date(c.created_at).toLocaleDateString()}</span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="empty-message">No claims history</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default SummaryPage;